### ISSUE TITLE
Basic ownCloud integration in GIG Mobile [4w]

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/home#11]
## GOAL:

We want to use ownCloud as storage backend and for dropbox-like features.

## DESCRIPTION:

- OwnCloud has an Android and iOS library, which should be integrated into the Rogerthat platform. 
- Users should be able to list/upload/download/view files of the storage backend. 
- Authentication must happen using ItsYouOnline.
- The ownCloud pages which are shown in the app should also be rebrandable. Meaning that they have the same colors as the app is plugged into.

## LINKS:

[kanban](https://waffle.io/rogerthat-platform/home?milestone=2.Y%20-%20storage%20box)

## REMARKS:

/

**Comment by RubenMattan** [comment]
not relevant anymore
