### ISSUE TITLE
Allow styling of news items

### ISSUE THREAD

**Issue by rvanoverbeke** [rogerthat-platform/home#3]
Our customers should be able to style the news they publish (eg: show certain blocks of text in italic or bold, show a list, ...)
Isn't it possible to allow for a pre-defined amount of html-tags to be used?

**Comment by lucasvanhalst** [comment]
I would use markdown for this https://uncodin.github.io/bypass/

**Comment by rvanoverbeke** [comment]
I'm all for markdown as well, I just wasn't sure how much work it would be to implement
